### ISSUE TITLE
Some Typo Errors on the ScoreLab Website

### ISSUE THREAD

**Issue by Grumpyyash** [scorelab/Webiu#118]
**This is not a technical issue, typo error in props passed to opportunities section of website**

On the ScoreLab website, under the opportunities section https://scorelab.org/opportunities we have some typo errors including misspelt words and grammatical typos as shown in the image - 

![Inkedissue_LI](https://user-images.githubusercontent.com/62200066/113332761-3a950700-933f-11eb-992a-4d6c1959b14d.jpg)

The 'required' word needs to be corrected and some other spelling mistakes need to be addressed!

**Comment by Grumpyyash** [comment]
I would request mentors to have a look at this minor typo issue :)

**Comment by rijusougata13** [comment]
@Grumpyyash  can i work on this?

**Comment by Grumpyyash** [comment]
@rijusougata13 this is an issue with props or the data passed to the component, we don't have access to that, maintainers will take care of it!

**Comment by Grumpyyash** [comment]
Resolved!
