### ISSUE TITLE
Create a Statistic component

### ISSUE THREAD

**Issue by nandkk05** [scorelab/Webiu#119]
We all know that for businesses the statistic component plays a very important role while representing their data to the clients. This section attracts the clients to get involved with the organization.

![Statistic](https://user-images.githubusercontent.com/33036554/113385797-731bfb80-93a6-11eb-81f4-607ba0b8a044.jpg)

Please review @wdevon99

**Comment by rijusougata13** [comment]
can i work on this ? @nandkk05

**Comment by nandkk05** [comment]
Hey @rijusougata13 really happy to hear this but I'm already working on it but I have a **suggestion** for you that you can design the CTA component.

Hope you don't mind :)

**Comment by rijusougata13** [comment]
@nandkk05  what is this CTA component ? can you explain?

**Comment by nandkk05** [comment]
@rijusougata13 CTA - **Call to Action** and here are some example templates - [link]( https://blog.hubspot.com/marketing/call-to-action-examples)

**Comment by nandkk05** [comment]
#160 Pull request created

**Comment by nandkk05** [comment]
#160

**Comment by Grumpyyash** [comment]
The statistics component was already added in one of the PRs #180 and #181. Thanks for your contribution @nandkk05 :)
