### ISSUE TITLE
Twitter link not available on scorelab website footer

### ISSUE THREAD

**Issue by Grumpyyash** [scorelab/Webiu#136]
On the scorelab official website https://scorelab.org/ in the footer, a Twitter icon is present as visible - 

![footer](https://user-images.githubusercontent.com/62200066/114266188-9a13a680-9a12-11eb-84a0-397e6cf0492f.png)

But, it is taking users to the official Twitter page, not on scorelab Twitter profile.
It might be due to scorelab currently do not have a Twitter account or the link for it was not pasted. Thus, I would request @charithccmc and @wdevon99 to have a look at this issue and maybe we could remove the icon for now if we do not have a Twitter account for scorelab currently.

**Comment by saif-malik-01** [comment]
@Grumpyyash hello sir , can you plz assign this task to me . If  the redirected link are not added or any other issue which let it stop to redirected to scorelab Twitter page , I will find it out and solve it .

**Comment by Grumpyyash** [comment]
Hi @saif-malik-01 thanks for showing interest but this is not an issue with the existing project repo but it has to do with props passed in the actual website and mentors will take care of this as we do not have its access

**Comment by saif-malik-01** [comment]
Okay , Thanks for info :D
