### ISSUE TITLE
Using many UI libraries in WebiU generalized website builder

### ISSUE THREAD

**Issue by gdsghost** [scorelab/Webiu#145]
Currently, we are using the following major UI libraries in developing our reusable Gatsby components as mentioned in the [package.json](https://github.com/scorelab/Webiu/blob/master/package.json) file.

1. Bootstrap
2. React Bootstrap
3. Ant Design

![PackageScreenshot](https://user-images.githubusercontent.com/48345668/114345308-162afd00-9b7f-11eb-8dcb-af9a0baf6331.PNG)

This will result in increasing app build sizes when using WebiU components.

**Comment by gdsghost** [comment]
I would request mentors @charithccmc  and @wdevon99  to please review this issue and confirm the UI library which should use in components so that I would love to migrate any other component to use the selected UI library.

**Comment by Grumpyyash** [comment]
Ant-design was used just for the pagination component. We might think of migrating things to one library in the future. Thanks for your interest and contribution @gdsghost :)
