### ISSUE TITLE
Create a reusable Coming Soon page component

### ISSUE THREAD

**Issue by gdsghost** [scorelab/Webiu#149]
A coming soon page which is also known as an under-construction page is a placeholder that sits on a website before the website or product is ready. Essentially, it's a temporary homepage to tell any website visitors that the site/product is being built and a way to capture leads before its launch.
Currently, we don't have a component to use to build a Coming Soon Page. What I wish to develop is a component that is reusable and also customizable via props

**Comment by Grumpyyash** [comment]
Timestamp and countdown components were added in #180. Thanks for your contribution @gdsghost :)
