### ISSUE TITLE
Create Timeline component

### ISSUE THREAD

**Issue by orendrasingh** [scorelab/Webiu#154]
![image](https://user-images.githubusercontent.com/44982473/114594697-293aeb80-9cab-11eb-9e5a-fd4f2fc0ec18.png)

I want to create a timeline component which can be resuable and will look something like this or even more better.

**Comment by Grumpyyash** [comment]
Hi @orendrasingh good thoughts on this, but I guess 2 similar PRs #57 and #63 have already been there and are to be reviewed and merged by mentors. 
Anyways, you can open another and mentors will review the better one :)

**Comment by Grumpyyash** [comment]
This has already been created in #180. Thanks for your contribution @orendrasingh :)
