### ISSUE TITLE
Create reusable card component

### ISSUE THREAD

**Issue by orendrasingh** [scorelab/Webiu#155]
![image](https://user-images.githubusercontent.com/44982473/114594944-7454fe80-9cab-11eb-8740-778e77e44f2e.png)
![image](https://user-images.githubusercontent.com/44982473/114598146-2fcb6200-9caf-11eb-809e-9184560748c2.png)

this will help in showcasing different kind of card design and customization by passing different parameters.

**Comment by Grumpyyash** [comment]
The card component has been created in PR #180. Thanks for your contribution @orendrasingh :)
