### ISSUE TITLE
Publication link not given on the SCoRe Lab Website

### ISSUE THREAD

**Issue by Grumpyyash** [scorelab/Webiu#157]
**This is an issue with the actual scorelab website, not the Webiu project codebase**
On the scorelab website https://scorelab.org/ under the publication section on the home page, we have a publication titled 'Smart mobile payment system' which does not take to the actual publication published instead it redirects to the publications page https://scorelab.org/publications/ as shown - 

![issue](https://user-images.githubusercontent.com/62200066/115149839-7dffad00-a083-11eb-9950-81856960f322.png)

I believe this is an issue with the link-prop passed to that particular publication item and updating the link prop to the correct one will resolve this issue

**Comment by Grumpyyash** [comment]
I would request mentors @charithccmc and @wdevon99 to please look into this :)

**Comment by soham4abc** [comment]
I can fix this. Can you provide the correct link which is to be replaced?

**Comment by Grumpyyash** [comment]
> I can fix this. Can you provide the correct link which is to be replaced?

It's not an issue with the current project, it's an issue in production props which we don't have access to

**Comment by soham4abc** [comment]
> I would request mentors @charithccmc and @wdevon99 to please look into this :)



> > I can fix this. Can you provide the correct link which is to be replaced?
> 
> It's not an issue with the current project, it's an issue in production props which we don't have access to

Okay, Thank you!!
