### ISSUE TITLE
Create a reusable Pricing component

### ISSUE THREAD

**Issue by gdsghost** [scorelab/Webiu#161]
Displaying pricing is an important feature of any business or organizational website especially offering services.
If the pricing isn't displayed on the website and people keep emailing for a quote, responding to those emails is going to take a ton of time. Having the pricing on the website allows potential clients to figure out what services will cost them without having to respond to every single email inquiry.

Currently, the generalized website builder does not have any reusable component responsible for showing pricing.
what should achieve is a reusable and customizable pricing component where variants could be updated and customized using props.

**Comment by Grumpyyash** [comment]
Pricing and Services components were further added in one of the PRs. Thanks for your contribution @gdsghost :)
