### ISSUE TITLE
Fix the home screen distortion

### ISSUE THREAD

**Issue by Grumpyyash** [scorelab/Webiu#186]
**The Bug**
The home screen is not so responsive across screens and becomes distorted once the screen size is reduced

**To Reproduce**
1. Start the server
2. Do not import any component, leave it up to the home itself
3. see the error

**Expected behavior**
The text should be responsive across all screens, including fonts too.

![responsive](https://user-images.githubusercontent.com/62200066/135709115-36de1514-755f-4579-b5e8-419de8e6d865.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS/Windows]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Browser [e.g. mozilla, safari]

**Comment by 1337-ishaan** [comment]
Pls assign me this issue
