### ISSUE TITLE
Create a component to show the list of contributors to a Github project

### ISSUE THREAD

**Issue by wdevon99** [scorelab/Webiu#20]
# Goal

Create a component to show the list of contributors to a specific Github project.
**Note**: Using Github API is suggested

**Comment by itsthecheat** [comment]
Hello, I'd be happy to work on this if available!

**Comment by khai93** [comment]
I'll try this today, if no ones working on it.

**Comment by wdevon99** [comment]
Sure, Submit a PR :) @itsthecheat / @khai93

**Comment by Grumpyyash** [comment]
@wdevon99  do you want something like this?
![github-api](https://user-images.githubusercontent.com/62200066/106904178-dc71ec00-6720-11eb-8098-bb768b2abfe8.png)

**Comment by wdevon99** [comment]
@Grumpyyash Yes! Have you used the GitHub API ? Also style on this could improve :)

**Comment by Grumpyyash** [comment]
Yes, definitely I will improve the styling. I have used the github api to get info about contributers of a project

**Comment by Grumpyyash** [comment]
![api](https://user-images.githubusercontent.com/62200066/107035392-1f45c980-67de-11eb-8262-ef279c101b36.png)
Should I generate a PR @wdevon99 ?

**Comment by Grumpyyash** [comment]
Already completed in #179
