### ISSUE TITLE
Add a feature to Navigation 

### ISSUE THREAD

**Issue by Ravindu-Hirimuthugoda** [scorelab/Webiu#209]
After we navigate to a particular page, It will be more user-friendly by showing the directed page name in different color(green) in the navigation bar.

(eg:- After we directed to the Home page, we can show Home in navigation bar in a different color(like green). So it will be more user friendly :) )

**Comment by adarrssh** [comment]
Hi, Can I work on this issue?

**Comment by AjayGurjar1** [comment]
i want to work on this issues please assign me this issue @Ravindu-Hirimuthugoda
