### ISSUE TITLE
Improve the "Links" Component to make it possible to include an icon for the link

### ISSUE THREAD

**Issue by wdevon99** [scorelab/Webiu#21]
# Goal

Improve the "Links" Component to make it possible to include an icon for the link

**Screenshot of current Link Component**

<img width="573" alt="Screenshot 2020-10-11 at 11 42 12" src="https://user-images.githubusercontent.com/28486947/95671621-ddea3800-0bb6-11eb-9c68-c0caf9f82746.png">

**Comment by sanskar-p** [comment]
Hi @wdevon99, I'd like to work on this issue.

**Comment by wdevon99** [comment]
@sanskar-p Sure, make it as generic as possible,

Note: The icon should an optional prop

**Comment by sanskar-p** [comment]
@wdevon99, I'm unable to setup and start the project locally. Here is the error I'm getting:

On running `npm install`
![image](https://user-images.githubusercontent.com/54014518/95720239-9cc55700-0c8e-11eb-9ba9-c668c92e7499.png)

On running `npm start`
![image](https://user-images.githubusercontent.com/54014518/95720268-a484fb80-0c8e-11eb-9873-99fab279ac55.png)

**Comment by pranay-simejia** [comment]
is this issue still open?
@wdevon99 , if yes I would like to work on it.

**Comment by wdevon99** [comment]
Yes its open @pranay-simejia

**Comment by wdevon99** [comment]
> @wdevon99, I'm unable to setup and start the project locally. Here is the error I'm getting:
> 
> On running `npm install`
> ![image](https://user-images.githubusercontent.com/54014518/95720239-9cc55700-0c8e-11eb-9ba9-c668c92e7499.png)
> 
> On running `npm start`
> ![image](https://user-images.githubusercontent.com/54014518/95720268-a484fb80-0c8e-11eb-9873-99fab279ac55.png)

Try adding that missing plugin

**Comment by Grumpyyash** [comment]
@wdevon99 do you want something like this?
![links](https://user-images.githubusercontent.com/62200066/106787906-42ee0000-6676-11eb-8199-ee52fe87b880.png)
I have implemented in links-component.

**Comment by Grumpyyash** [comment]
Already completed in #173
