### ISSUE TITLE
Webpack Errors while running project 

### ISSUE THREAD

**Issue by Abhijay007** [scorelab/Webiu#216]
**Describe the bug**

File to import not found : ./variables.sass  in src/styles/style.sass
and undefined variable in src/style/font.sass

**To Reproduce**
run the project locally and these wepack errors pop up 

**Expected behavior**

the project should compile successfully and run on localhost: 3000 

**Screenshots**

![Screenshot 2022-04-18 155916](https://user-images.githubusercontent.com/64387054/163828576-1206e43b-5352-4aae-8973-e48bbd99ecde.png)

![Screenshot 2022-04-18 155937](https://user-images.githubusercontent.com/64387054/163828592-0f862d38-89a4-4622-b3a8-16aad043feaf.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser  : chrome]

**Comment by Abhijay007** [comment]
I will open PR for this issue soon :)

**Comment by vaishak10** [comment]
@Abhijay007  Where did you find the `variables.sass` file. Was facing the same issue.
