### ISSUE TITLE
Create a Navbar component of First theme 

### ISSUE THREAD

**Issue by Abhijay007** [scorelab/Webiu#219]
As per provided designs, create a Navbar component for the First theme. 

![image](https://user-images.githubusercontent.com/64387054/175566739-ed53be92-a2d4-4c3c-9e86-0c2919a972f7.png)

Reference for the design: https://www.figma.com/file/0ISIz6XklEToDd4KXfIWRB/SCoRe-Lab-Theme-designs?node-id=0%3A1

Cc: @charithccmc , @dinithminura

**Comment by adarrssh** [comment]
Hi, is anyone working on this issue?
I would like to work on this issue.
