### ISSUE TITLE
Create a reusable Search Bar Component

### ISSUE THREAD

**Issue by wdevon99** [scorelab/Webiu#22]
# Goal

Create a reusable Search Bar Component. 
**Note:** This should be a generic Search Bar which can be customized via props.

**Comment by sanskar-p** [comment]
Hi @wdevon99, I'd like to work on this. What kinds of props are you looking for?

**Comment by wdevon99** [comment]
@sanskar-p Sure!

- The search bar basic input props such as "onChange" 
- Also should be able to override styles with props (eg: "containerStyle" prop)

These are just some, you can be creative and make it very generic and highly customizable.

**Comment by kartikmandhan** [comment]
hi @wdevon99 , I would like to work on this, but on cloning the project and after installing the dependencies, i get a error can you help me resolve this error so i can start working on this issue
![Screenshot 2021-01-16 at 7 27 24 PM](https://user-images.githubusercontent.com/56060122/104813706-dfb83d00-5830-11eb-96c7-bb5219cbb117.png)

**Comment by wdevon99** [comment]
Hi @kartikmandhan try mannualy adding the missing plugin :)

**Comment by pranay-simejia** [comment]
is this issue open? Is there any specific design for the search bar UI?

**Comment by kenkirito** [comment]
can i work on this

**Comment by ffalpha** [comment]
Is this issue still open ?

**Comment by pranay-simejia** [comment]
@wdevon99 can you review my PR?

**Comment by Grumpyyash** [comment]
Already completed in #176
