### ISSUE TITLE
Add the search functionality to the Project List Component

### ISSUE THREAD

**Issue by wdevon99** [scorelab/Webiu#23]
# Goal

Use the Reusable Search Bar Component to add the search functionality to the Project List Component.
**Note:** Before Starting this issue, #22 issue should be completed.

**Comment by tranjenny** [comment]
can i try?

**Comment by wdevon99** [comment]
Sure @tranjenny

**Comment by tranjenny** [comment]
Are you using the Gatsby framework?

**Comment by Grumpyyash** [comment]
Is this what you want @wdevon99 ? I have implemented whole functionality on sample data, should I generate a PR?
Search functionality is working well with filtering projects by their name.
![home](https://user-images.githubusercontent.com/62200066/107115531-490cf800-6893-11eb-8615-534c720b3003.png)

**Comment by ffalpha** [comment]
Is this issue still open ?

**Comment by Grumpyyash** [comment]
Already completed in #178
