### ISSUE TITLE
Create a suitable logo for Webiu

### ISSUE THREAD

**Issue by wdevon99** [scorelab/Webiu#24]
WEBIU

Building and maintaining a website is an essential task for any business or organization. This project aims to ease the workflow of getting a website up and running by developing reusable Gatsby Components which are easily plugable to create Gatsby websites with ease.

**Based on this description, create a suitable logo for Webiu!**

**Comment by HarshCasper** [comment]
Hello @wdevon99 

I am looking to get started with contributing to Score Lab. In the past, I have led some Product Development Teams, and I would be interested to work on this particular Issue. 

Kindly let me know if I can start working on the same. In addition, I would like to know a few details for the following: 

- On which directory should the PR be made? 
- Should README be updated correspondingly? 

I am excited to get working on this.

**Comment by wdevon99** [comment]
Fork the repo and place PRs to this repo

You can find more info here: https://scorelab.org/gsoc @HarshCasper

**Comment by kenkirito** [comment]
can i work on this issue

**Comment by ineffable23** [comment]
Hey @wdevon99  
I am highly interested in this issue.

**Comment by Grumpyyash** [comment]
Already completed in #182. Thank you all for your interest :)
