### ISSUE TITLE
A Separate Component for different types of loaders

### ISSUE THREAD

**Issue by sachinsom93** [scorelab/Webiu#30]
# Goal
### As the main purpose of this project Webiu to to ease the workflow of getting a website up and running by developing reusable Gatsby Components which are easily plugable to create Gatsby websites with ease. And, this project doesn't contain any reusable loader, So We can create a separate component for different types of loaders.
Usually we don't need a loader  in  Gatsby site as Gatsby sites usually fast. But in some situations we need it. For example if our users have poor WiFi or or slow 2G/3G connections then it would be a good idea to have loader  before contents load or before fetching contents from a CRM or external API. 
 
What's your opinion @wdevon99 ?
#### I have raised a PR for this issue, should I add more things ?

**Comment by Grumpyyash** [comment]
The loader component was added in a further PR #182. Thanks for your contributions @sachinsom93 :)
