### ISSUE TITLE
Create a footer Component for the Fourth theme

### ISSUE THREAD

**Issue by Abhijay007** [scorelab/Webiu#346]
As per provided designs, Create a footer Component for the Fourth theme

![image](https://user-images.githubusercontent.com/64387054/185804897-8d7457b1-ab50-44e8-80f9-c4bbeddf9022.png)

Reference for the design: https://www.figma.com/file/0ISIz6XklEToDd4KXfIWRB/SCoRe-Lab-Theme-designs?node-id=3%3A2

Cc: @charithccmc, @dinithminura

**Comment by rakshitgondwal** [comment]
Hey! I would like to contribute to this issue. Can you tell me that how should I proceed with this? @Abhijay007
