### ISSUE TITLE
Create a Contact us component for the forth theme

### ISSUE THREAD

**Issue by Abhijay007** [scorelab/Webiu#353]
As per provided designs, Create a Contact us component for the fourth theme

![image](https://user-images.githubusercontent.com/64387054/186727404-24e3b346-6aca-4117-9cfa-3c041f965e11.png)

Reference for the design: https://www.figma.com/file/0ISIz6XklEToDd4KXfIWRB/SCoRe-Lab-Theme-designs?node-id=3%3A2

Cc: @charithccmc, @dinithminura

**Comment by shoebilyas123** [comment]
Hi @Abhijay007 . I would like to work on this issue.
