### ISSUE TITLE
[Feature Request]Creating a color pelette 

### ISSUE THREAD

**Issue by sachinsom93** [scorelab/Webiu#36]
### Problem and Solution
Currently the project contains some variables in style directory inside src directory for colors, breakpoints and transitions, but this would be refactored to different sub-folders of color-variables, animation-variables, transition-variables and breakpoints-variables.
It would make developer's job way more easy for color choosing, using varieties of colors without worrying about their hex code.

### Additional Context and Screenshots
I am working on this feature and created a color-pelette of 150+ colors.
![color-pelette](https://github.com/sachinsom93/temp/blob/master/example1.jpg?raw=true)
![color-pelette](https://github.com/sachinsom93/temp/blob/master/example2.jpg?raw=true)
Also I am creating variables for transitions and animations.
Suggestions and discussions would be appreciated  from the community @wdevon99 @charithccmc .
I am working on this and expected to open a PR soon.

**Comment by Grumpyyash** [comment]
Any progress on this @sachinsom93?
