### ISSUE TITLE
Create a Card Grid Component for the Fourth theme 

### ISSUE THREAD

**Issue by Abhijay007** [scorelab/Webiu#387]
As per provided designs, Create a Card Grid Component for the Fourth theme 

![image](https://user-images.githubusercontent.com/64387054/190557914-14394427-043a-488a-8792-0a2bf89fea70.png)

Reference for the design: https://www.figma.com/file/0ISIz6XklEToDd4KXfIWRB/SCoRe-Lab-Theme-designs?node-id=3%3A2

Cc: @charithccmc, @dinithminura

**Comment by kshitijarvikar** [comment]
I would like to do this, but if you could explain what exactly one has to do in this it would be super helpfull!!
