### ISSUE TITLE
Create Documentation for existing components using https://storybook.js.org

### ISSUE THREAD

**Issue by ffalpha** [scorelab/Webiu#39]
Storybook is an open source tool for developing UI components in isolation .It allows you to browse a component library, view the different states of each component, and interactively develop and test components. Adding Documentation for existing components using Storybook will help for future developers Currently Webui doesn't have proper documentation for existing components

**Comment by Grumpyyash** [comment]
Storybook documentation has been done in #184. Thanks for your contributions @ffalpha :)
