### ISSUE TITLE
Create a Footer Section Component for the Fifth theme 

### ISSUE THREAD

**Issue by Abhijay007** [scorelab/Webiu#398]
As per provided designs, Create a Footer Section Component for the Fifth theme 

![image](https://user-images.githubusercontent.com/64387054/192531641-8a487028-cbd8-47d4-a531-560274df99fd.png)

Reference for the design: https://www.figma.com/file/0ISIz6XklEToDd4KXfIWRB/SCoRe-Lab-Theme-designs?node-id=3%3A4

Cc: @charithccmc, @dinithminura

**Comment by vaibhavi-roy** [comment]
I want to work on this issue @Abhijay007 
Please assign this task to me
Thank you
