### ISSUE TITLE
Create a Contact Us component for the fifth theme 

### ISSUE THREAD

**Issue by Abhijay007** [scorelab/Webiu#399]
As per provided designs, Create a Contact Us component for the fifth theme e

![image](https://user-images.githubusercontent.com/64387054/192532750-b9a3910a-98ec-4535-998f-6b4e87dd98a3.png)

Reference for the design: https://www.figma.com/file/0ISIz6XklEToDd4KXfIWRB/SCoRe-Lab-Theme-designs?node-id=3%3A4

Cc: @charithccmc, @dinithminura

**Comment by AryanMankame** [comment]
Hi! Can I be assigned for this task?
