### ISSUE TITLE
twitter link not working

### ISSUE THREAD

**Issue by lingeshwaran05** [scorelab/Webiu#407]
**Describe the bug**
In footer , twitter link redirects to home twitter page not into scorelab twitter page

**To Reproduce**

**Expected behavior**
A detailed description of the expected behaviour

**Screenshots**
If possible, please use screenshots
![image](https://user-images.githubusercontent.com/76167753/193601844-540743a3-7edd-4a66-9692-7279a59a51d1.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS/Windows]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**
 - Browser [e.g. mozilla, safari]

**Comment by lingeshwaran05** [comment]
am newbie so can you please assign it to me and add labels

**Comment by rksingh2001** [comment]
Can I take up this issue?

**Comment by vednp** [comment]
Hello I can fix the Twitter link please assign me the issue

**Comment by lingeshwaran05** [comment]
#423

**Comment by aditi5050** [comment]
I would like to work on this issue, please assign this to me.

**Comment by AjayGurjar1** [comment]
i want to work on this issues please assign me this issue @lingeshwaran05
