### ISSUE TITLE
Add Favicon for Webiu 

### ISSUE THREAD

**Issue by sachinsom93** [scorelab/Webiu#41]
Once the logo is designed as mentioned in issue #24 , it is required to design favicon similar to the logo which will be used in project frontend.

**Comment by ineffable23** [comment]
I'm interested in this issue, please assign it to me. Can you please guide me regarding the same?

**Comment by Grumpyyash** [comment]
As of now, we will use the same favicon as of SCoRe Lab website. Thanks for your contribution @sachinsom93 :)
