### ISSUE TITLE
Add Null Check to components

### ISSUE THREAD

**Issue by sachinsom93** [scorelab/Webiu#42]
### Problem
There are some components in which null check of props are not done.
Components without null check of props
1. ButtonWithHeading
2. Contact
3. Footer
4. GitterRoomItem
5. Guildlines
6. MediumFeed
7. pageNotFound

**Comment by neelesh17** [comment]
Hey @sachinsom93, I would like to work on this issue.

**Comment by Grumpyyash** [comment]
This was done in further PRs. Thanks for your contribution @sachinsom93 :)
