### ISSUE TITLE
gatsby-plugin-manifest issue

### ISSUE THREAD

**Issue by subodhk01** [scorelab/Webiu#51]
`gatsby-plugin-manifest` is throwing a Plugin Error

<img width="397" alt="Screenshot 2021-02-16 at 6 42 24 PM" src="https://user-images.githubusercontent.com/19875783/108067394-b7696b80-7086-11eb-9efb-4717213e48ed.png">

**Comment by Grumpyyash** [comment]
This issue was fixed in one of the PRs. Thanks for your contributions @subodhk01 :)
