### ISSUE TITLE
Small typo error in " https://www.scorelab.org/"

### ISSUE THREAD

**Issue by rajitha1998** [scorelab/Webiu#66]
"heip" should be changed as "help"

![Screenshot from 2021-03-01 16-29-22](https://user-images.githubusercontent.com/36359382/109488726-f1d20000-7aab-11eb-9282-a156f3e486b5.png)

**Comment by Grumpyyash** [comment]
I think all the content which is present on the website https://www.scorelab.org/ has been passed as props to the components of scorelab/webiu project. So, I think the code of this repo is correct we just need to fix the GsocIdeaList-component's "description" prop which I don't have access to. It must be on the codebase of the Scorelab website.
@wdevon99 must be having that codebase's props access.
