### ISSUE TITLE
Github URL is wrong for ImageLab in "scorelab.org/gsoc/" 

### ISSUE THREAD

**Issue by ffalpha** [scorelab/Webiu#67]
Under the  2: ImageLab - Extend the ImageLab functionality
**Github URL should be : - https://github.com/scorelab/imagelab**

![1112](https://user-images.githubusercontent.com/31257148/109512160-ceb64900-7ac9-11eb-802b-f0f49e7dd652.PNG)

**Comment by SyedAnwarHashmi** [comment]
Hello, I am working on this.

**Comment by Grumpyyash** [comment]
I think this is also because of a typo error in the props data  of 'listItems.githuburl' prop in the GsocIdeaList component.

**Comment by Grumpyyash** [comment]
A typo bug related to markdown data in the website, not specific to project, thanks for your contribution @ffalpha :)
