### ISSUE TITLE
Create a sliding Signin Signup form.

### ISSUE THREAD

**Issue by pranay-simejia** [scorelab/Webiu#72]
I really like the idea of sliding forms. Would you like me to integrate it with Webiu? @wdevon99 
Do suggest design changes.

![slidingform](https://user-images.githubusercontent.com/70064696/110240549-850aaa00-7f72-11eb-8746-20f062fb8c0c.gif)

**Comment by Mayank-contradiction** [comment]
Can I help you to create this sliding form?

**Comment by pranay-simejia** [comment]
I have already created it! Thanks though.

**Comment by Grumpyyash** [comment]
Signup and login forms have been created in #181. Thanks for your contribution @pranay-simejia :)
