### ISSUE TITLE
bug: few problems setting up dev environment

### ISSUE THREAD

**Issue by aditya-mitra** [scorelab/Webiu#88]
## Missing Package

- The package *gatsby-plugin-fontawesome-css* is missing.

![prd1](https://user-images.githubusercontent.com/55396651/111039491-58640000-8454-11eb-852c-21449c68419c.png)

## Minor Errors in `gatsby-config`

- The `icon` for _gatsby-plugin-sharp_ is missing
- The `path` in _gatsby-plugin-react-helmet_ is incorrect

![prd 3](https://user-images.githubusercontent.com/55396651/111039496-5c901d80-8454-11eb-92e4-429f0faaf88b.png)
![prd 4](https://user-images.githubusercontent.com/55396651/111039498-5e59e100-8454-11eb-9469-030c3abfe4db.png)

## Import Error in Sass Files

- There were import errors in the _sass_ files inside _src/styles_

![prd 2](https://user-images.githubusercontent.com/55396651/111039493-5ac65a00-8454-11eb-8f7f-5b863fb54df0.png)

**Comment by Grumpyyash** [comment]
These errors were due to deprecated packages and are resolved in #168. Thanks for your contribution @aditya-mitra :)
