### ISSUE TITLE
Cant able to run a app

### ISSUE THREAD

**Issue by Vishv07** [scorelab/Webiu#93]
![image](https://user-images.githubusercontent.com/37216460/111183899-68a3e880-85d6-11eb-8590-f6f16ef1ab7c.png)

Getting this error while starting the server.

and here's my config file

module.exports = {
  siteMetadata: {
    title: `Webiu`,
    description: `Building and maintaining a website is an essential task for any business or organization. This project aims to ease the workflow of getting a website up and running by developing a “generalized website builder”, with the help of the Gatsby Js Framework. The individuals would be able to utilize this generalized platform to plug-in required modules and configure the datasource as per requirements to build custom websites for their organizations.`,
    author: `@ScoreLab`,
  },
  plugins: [
    `gatsby-plugin-fontawesome-css`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data`,
        name: `data`,
      },
    },
    `gatsby-transformer-remark`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        display: `minimal-ui`,
      },
    }
  ],
}

**Comment by SaurabhSonde** [comment]
> ![image](https://user-images.githubusercontent.com/37216460/111183899-68a3e880-85d6-11eb-8590-f6f16ef1ab7c.png)
> 
> Getting this error while starting the server.
> 
> and here's my config file
> 
> module.exports = {
> siteMetadata: {
> title: `Webiu`,
> description: `Building and maintaining a website is an essential task for any business or organization. This project aims to ease the workflow of getting a website up and running by developing a “generalized website builder”, with the help of the Gatsby Js Framework. The individuals would be able to utilize this generalized platform to plug-in required modules and configure the datasource as per requirements to build custom websites for their organizations.`,
> author: `@ScoreLab`,
> },
> plugins: [
> `gatsby-plugin-fontawesome-css`,
> `gatsby-plugin-sass`,
> `gatsby-plugin-react-helmet`,
> {
> resolve: `gatsby-source-filesystem`,
> options: {
> path: `${__dirname}/src/data`,
> name: `data`,
> },
> },
> `gatsby-transformer-remark`,
> `gatsby-transformer-sharp`,
> `gatsby-plugin-sharp`,
> {
> resolve: `gatsby-plugin-manifest`,
> options: {
> name: `gatsby-starter-default`,
> short_name: `starter`,
> start_url: `/`,
> display: `minimal-ui`,
> },
> }
> ],
> }

PRs are already opened for these issue but not yet reviewed by mentors.

**Comment by SaurabhSonde** [comment]
PRs are already opened for these issue but not yet reviewed by mentors.

**Comment by Vishv07** [comment]
Okay

**Comment by Grumpyyash** [comment]
This issue was fixed in one of the PR! Thanks for your contribution @Vishv07 @SaurabhSonde :)
