### ISSUE TITLE
Sass error at the time of local setup

### ISSUE THREAD

**Issue by SaurabhSonde** [scorelab/Webiu#95]
![image](https://user-images.githubusercontent.com/53482872/111861026-17e31580-8971-11eb-8084-4bb494fdc9e4.png)

As i notice these error occurs to many of new contributors who are trying to setup these project locally.I have work on these and notice that these error occurs due to older version of gatsby-plugin-sass and node-sass.So I am updating both packages and opening a PR for these issue very soon.

**Comment by Grumpyyash** [comment]
This was resolved in a further PR #168. Thanks for your contribution @SaurabhSonde :)
